Update SQL plugin relevance functions documentation
Yury-Fridlyand/documentation-website pull request #1
Opened 2022-07-06 20:42 UTC by Yury-Fridlyand

Signed-off-by: Yury Fridlyand <yuryf@bitquilltech.com>

2022-07-06 23:25 UTC, Yury-Fridlyand commented
[Full-Text Search - OpenSearch documentation.pdf](https://github.com/Yury-Fridlyand/documentation-website/files/9059181/Full-Text.Search.-.OpenSearch.documentation.pdf)

2022-07-06 23:59 UTC, Yury-Fridlyand commented
TODO:
* mention PPL in SQL
* Validate and/or delete information about [`delete`](https://opensearch.org/docs/latest/search-plugins/sql/delete/)
* Add more functions and examples
* Mention `explain` request

2022-07-13 00:00 UTC, MitchellGale-BitQuill approved these changes

2022-07-13 00:16 UTC, joshuali925 approved these changes
question: why move PPL section under SQL plugin? i believe they were in different sections because their use cases are different

2022-07-13 01:27 UTC, Yury-Fridlyand commented
> question: why move PPL section under SQL plugin? i believe they were in different sections because their use cases are different

Well, yes. Following this approach, I have to return PPL back.
The idea was: PPL provided and maintained by the SQL Plugin.

I'm open to move it back to Observability Plugin or add clearer references there or whatever we can find good for a user.

2022-07-13 21:03 UTC, forestmvey commented on _search-plugins/sql/sql/jdbc.md
> +## Connecing to Tableau
Connecting*

2022-07-13 21:15 UTC, acarbonetto requested changes

2022-07-13 21:15 UTC, acarbonetto commented on _observability-plugin/index.md
> +1. Explore data over a certain timeframe using [Piped Processing Language]({{site.url}}{{site.baseurl}}/search-plugins/sql/ppl/index).
We should keep a page in the Observability Plugin section that points to the SQL Plugin/PPL section

2022-07-13 21:15 UTC, acarbonetto commented on _search-plugins/sql/cli.md
> +parent: SQL Plugin - SQL & PPL
How about this for ordering of the SQL Plug - SQL & PPL section:
```
SQL PLugin - SQL & PPL
  Endpoint
  Protocol
  SQL CLI (Rename to CLI or "Command-Line Interface")
  SQL
    Query Workbench
    Basic Queries
    Complex Queries
    JSON Support
    Metadata Queries
    Aggregation Functions
    Delete
    JDBC Driver
    ODBC Driver
  PPL - Piped Processing Language
    Functions (Split into two pages: "General Syntax" and "PPL Functions")
  Identifiers
  Data Types
  Functions
  Full-Text Search
  Settings
  Troubleshooting
  Monitoring
  Limitations
  
```

2022-07-13 21:18 UTC, acarbonetto commented
> > question: why move PPL section under SQL plugin? i believe they were in different sections because their use cases are different
> 
> Well, yes. Following this approach, I have to return PPL back. The idea was: PPL provided and maintained by the SQL Plugin.
> 
> I'm open to move it back to Observability Plugin or add clearer references there or whatever we can find good for a user.

It makes sense to move it to the SQL Plugin section, as the PPL syntax is mostly just a variation of the SQL query syntax, but also shares a lot of the same tooling. 

@Yury-Fridlyand let's make sure to preserve a section in the Observability plugin that refers tot the PPL section of the SQL plugin, so that we don't lose that reference.  Otherwise, I think most content should be in the SQL plugin section to avoid duplication.

2022-07-13 23:16 UTC, forestmvey commented
Not your code but this shouldn't be in the table of contents pane:

[sql/ppl/functions.md#L899](https://github.com/Yury-Fridlyand/documentation-website/blob/55f4652fc784d749ccfec52f84601910762e6d45/_search-plugins/sql/ppl/functions.md?plain=1#L899)

2022-07-13 23:17 UTC, forestmvey requested changes
Few minor changes requested.

2022-07-14 01:55 UTC, Yury-Fridlyand commented on _search-plugins/sql/cli.md
> -To install the SQL CLI:
These steps were required to build/launch CLI locally before it published on pip/pypi.

2022-07-14 15:34 UTC, forestmvey approved these changes

2022-07-14 17:04 UTC, Yury-Fridlyand commented
Please, see most recent changes made in c4a42dd and 60fd14b.

2022-07-20 08:21 UTC, MaxKsyunz commented on _search-plugins/sql/settings.md
> +There is another format of request which could be used:
Is this line necessary? I'm not sure what it's trying to say.

2022-07-22 02:50 UTC, Yury-Fridlyand commented on _search-plugins/sql/limitation.md
> -## SELECT FROM WHERE
No, V2 engine can do `SELECT 1;`.
Good point, I'll recover this in the end with corresponding note.

2022-07-22 03:09 UTC, Yury-Fridlyand commented on _search-plugins/sql/limitation.md
> -
No. I'm not sure that there is a valid response, but at least there is no error/failures:
```json
$ curl -H 'Content-Type: application/x-ndjson' -XPOST 'http://localhost:9200/conflict_index_1/_doc/?pretty' -d '{ "a": { "b": 1 } }'
{
  "_index" : "conflict_index_1",
  "_id" : "OwHfI4IBUwd-1Kul7tnr",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}

$ curl -H 'Content-Type: application/x-ndjson' -XPOST 'http://localhost:9200/conflict_index_2/_doc/?pretty' -d '{ "a": { "b": 1, "c2": 2 } }'
{
  "_index" : "conflict_index_2",
  "_id" : "PAHgI4IBUwd-1KulH9mg",
  "_version" : 1,
  "result" : "created",
  "_shards" : {
    "total" : 2,
    "successful" : 1,
    "failed" : 0
  },
  "_seq_no" : 0,
  "_primary_term" : 1
}
```
```console
opensearchsql> SELECT * FROM conflict_index*;
fetched rows / total rows = 2/2
+-------------------+
| a                 |
|-------------------|
| {'b': 1}          |
| {'b': 1, 'c2': 2} |
+-------------------+
```

2022-07-22 21:25 UTC, acarbonetto requested changes

2022-07-22 21:44 UTC, Yury-Fridlyand commented on _search-plugins/sql/endpoints.md
> +V2 query engine not only runs queries in OpenSearch engine but also supports post-processing for complicated queries. Accordingly, explain output is no longer pure OpenSearch DSL, but also includes q
Thanks, I move this phrase to `limitations`

2022-07-26 00:59 UTC, merged